### ISSUE TITLE
** BUILD FAILED ** IOS Device

### ISSUE THREAD

**Issue by vitorcalvi** [kanzitelli/rnn-starter#102]
react-native run-ios --device
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-ui-lib contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Found Xcode workspace "RNNStarter.xcworkspace"
info Using first available device named "Vitor Calvi’s iPhone" due to lack of name supplied.
info Building (using "xcodebuild -workspace RNNStarter.xcworkspace -configuration Debug -scheme RNNStarter -destination id=00008101-001358183A11001E")
(node:9197) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNNStarter.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RNNStarter.xcworkspace -configuration Debug -scheme RNNStarter -destination id=00008101-001358183A11001E

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: bc1e5c58d39926c543305e41031054a7
Build description path: /Users/vitorcalvi/Library/Developer/Xcode/DerivedData/RNNStarter-auwondskuqiyqrdncugpvcolpuwh/Build/Intermediates.noindex/XCBuildData/bc1e5c58d39926c543305e41031054a7-desc.xcbuild

note: Building targets in dependency order
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNNStarter' from project 'RNNStarter')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNNStarter' from project 'RNNStarter')
/Users/vitorcalvi/Desktop/lifee/ios/Pods/Pods.xcodeproj: error: Signing for "EXConstants-EXConstants" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'EXConstants-EXConstants' from project 'Pods')
/Users/vitorcalvi/Desktop/lifee/ios/Pods/Pods.xcodeproj: error: Signing for "React-Core-AccessibilityResources" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'React-Core-AccessibilityResources' from project 'Pods')
warning: Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')

2022-09-14 15:54:52.184 xcodebuild[9241:54221]  DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot2/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-21157/DTDeviceKitBase/DTDKRemoteDeviceData.m:382
Details:  (null) deviceType from 00008101-001358183A11001E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x12aa665c0>
Method:   -platform
Thread:   <NSThread: 0x12f604120>{number = 2, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

**Comment by kanzitelli** [comment]
You need to “Select a development team in the Signing & Capabilities editor.” as it’s stated in the error. Please, read the error carefully before posting the issue. You need to do it using XCode.

**Comment by vitorcalvi** [comment]
Thanks, but i did. Bellow follow the img link
https://i.imgur.com/2clyLed.png

**Comment by kanzitelli** [comment]
Hmm, that’s weird then, i’ve been testing debug and release modes yesterday and it was alright. Did you also run it through XCode?

**Comment by kanzitelli** [comment]
Also the weird thing is that it shows “(null)” for device type, maybe it can’t detect the device.

**Comment by vitorcalvi** [comment]
Unfortunately. AN issue that we can notice, i changed my node 18 to node 16. It maybe unstable the system. I Guess. I will try another things. I liked the RN Project and we will use to make our Apps

**Comment by kanzitelli** [comment]
Yes, React Native requires node 16 now, maybe that’s the problem. However, if you find the solution, let me know!

Great to hear that! Share your app once it’s done :)

And feel free to write here. I’ll close the issue for now then.

**Comment by vitorcalvi** [comment]
Thanks, In IOS Simulator is ok. Working pretty well.
But in IOS device it doen't working, can you help :)

react-native run-ios --device
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-ui-lib contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Found Xcode workspace "RNNStarter.xcworkspace"
info Using first available device named "Vitor Calvi’s iPhone" due to lack of name supplied.
info Building (using "xcodebuild -workspace RNNStarter.xcworkspace -configuration Debug -scheme RNNStarter -destination id=00008101-001358183A11001E")
(node:51409) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNNStarter.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RNNStarter.xcworkspace -configuration Debug -scheme RNNStarter -destination id=00008101-001358183A11001E

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 6a96db0001087a1bc7b185419dee2ce4
Build description path: /Users/vitorcalvi/Library/Developer/Xcode/DerivedData/RNNStarter-crdxbxjrvwlrdydjomatozgoixpd/Build/Intermediates.noindex/XCBuildData/6a96db0001087a1bc7b185419dee2ce4-desc.xcbuild

note: Building targets in dependency order
warning: Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
/Users/vitorcalvi/Desktop/rnn-starter/ios/Pods/Pods.xcodeproj: error: Signing for "EXConstants-EXConstants" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'EXConstants-EXConstants' from project 'Pods')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNNStarter' from project 'RNNStarter')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNNStarter' from project 'RNNStarter')
/Users/vitorcalvi/Desktop/rnn-starter/ios/Pods/Pods.xcodeproj: error: Signing for "React-Core-AccessibilityResources" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'React-Core-AccessibilityResources' from project 'Pods')

** BUILD FAILED **

**Comment by kanzitelli** [comment]
I don’t know, i always test on a real device in debug and release modes. Error says again that “Expo Constants” library requires a development team. What i would recommend is to clean the project, install node modules and pods again and run it through XCode (not terminal).

**Comment by vitorcalvi** [comment]
Great! I try by Xcode and Unsupported Swift version issue.
https://imgur.com/a/JKkXFMa

**Comment by kanzitelli** [comment]
that’s is okay, it doesn’t break anything. just press OK button and run the project.

**Comment by vitorcalvi** [comment]
It doesn't work 
https://imgur.com/a/9pL4Y5z

**Comment by vitorcalvi** [comment]
Android Studio doesn't work too
https://imgur.com/a/Q5nOdab

**Comment by kanzitelli** [comment]
try running ‘yarn android:adb’ script. if it won’t help, do ‘yarn android’.
also all the problems you mentioned are not starter’s issues, they are related to RN. please use google before posting them

**Comment by vitorcalvi** [comment]
Finally, it's working :)))) Working on Android and IPhone device 👍 Let's happy coding

**Comment by vitorcalvi** [comment]
Another, i did,  yarn rename "NewApp" -b com.yourcompany.newapp, but the ios folder is still in RNNStartet, i googled for change it and turn it in to my app name but i can't. Can you help me. Thanks
