### ISSUE TITLE
Incorrect peer dependency react-native-ui-lib > react-native-redash > use-memo-one@1.1.2

### ISSUE THREAD

**Issue by vitorcalvi** [kanzitelli/rnn-starter#106]
When trying to eas build a warning issue come up:
warning "react-native-ui-lib > react-native-redash > use-memo-one@1.1.2" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".

**Comment by kanzitelli** [comment]
the warning is coming from `react-native-ui-lib` and once they fix it, it will go. you can open issue in their repo. closing the issue.
