### ISSUE TITLE
React Native new Version support. 

### ISSUE THREAD

**Issue by FawadMahmood** [kanzitelli/rnn-starter#38]
Ios hermes engine in latest react native.

**Comment by kanzitelli** [comment]
Hi @FawadMahmood. Thank you for raising this up! I have started updating all libraries and React Native itself to the latest versions. Also planning to add more Best Practices. So it's going to be a big update and takes some time.

**Comment by FawadMahmood** [comment]
Looking forward to it, Thank you so much.

**Comment by kanzitelli** [comment]
Hi @FawadMahmood! I have just published a new version of the starter. It has the latest versions of each library. Also, I have improved the project structure and added some cool features. Enjoy! :)
