### ISSUE TITLE
Renaming the project doesn't work. 

### ISSUE THREAD

**Issue by Yasir5247** [kanzitelli/rnn-starter#43]
When i ran yarn rename "Aiminaabee" the files inside the ios directory doesn't rename to the new name. 

RNNStarter.xcodeproj
RNNStarter.xcworkspace
RNNStarter
RNNStarterTests

These files don't change. 

before renaming i updated the app.json file like so:
app.json 
{
  "name": "Aiminaabee",
  "displayName": "Aiminaabee"
}

What am I missing here.

**Comment by kanzitelli** [comment]
hi @Yasir5247. `yarn rename` command uses [react-native-rename](https://github.com/junedomingo/react-native-rename)'s script. So you need to run `yarn rename Aiminaabee` and then run `yarn ios:pods`, so it's fully applied for iOS. Let me know how it goes :)

**Comment by Yasir5247** [comment]
This is what i did

1- git clone https://github.com/kanzitelli/rnn-starter.git Aiminaabee && cd Aiminaabee
2- rm -rf .git
3- yarn && yarn ios:pods
4- yarn rename Aiminaabee
5- yarn ios:pods

I can still see the file names not changed inside the ios folder. 


❯ yarn rename Aiminaabee
yarn run v1.22.10
$ npx react-native-rename Aiminaabee
npx: installed 80 in 6.206s
Can't find an ios path or project. Make sure that the ios project path and property 'name' in app.json the same.
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee-tvOS
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee-tvOSTests
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee.xcodeproj
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee.xcodeproj/xcshareddata/xcschemes/Aiminaabee-tvOS.xcscheme
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee.xcodeproj/xcshareddata/xcschemes/Aiminaabee.xcscheme
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/AiminaabeeTests
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/AiminaabeeTests/AiminaabeeTests.m
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee.xcworkspace
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee/Aiminaabee.entitlements
Ignore above error if this file doesn't exist
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/ios/Aiminaabee-Bridging-Header.h
Ignore above error if this file doesn't exist
/android/app/src/main/res/values/strings.xml MODIFIED
/index.js MODIFIED
/package.json MODIFIED
/app.json MODIFIED
/android/settings.gradle MODIFIED
/ios/Podfile MODIFIED
/app.json MODIFIED
android/app/src/main/java/com/rnnstarter BUNDLE IDENTIFIER CHANGED
/android/app/src/main/AndroidManifest.xml MODIFIED
/android/app/_BUCK MODIFIED
/android/app/build.gradle MODIFIED
/android/app/src/main/java/com/rnnstarter/MainActivity.java MODIFIED
/android/app/src/main/java/com/rnnstarter/MainApplication.java MODIFIED
/android/app/src/main/java/com/rnnstarter/MainActivity.java MODIFIED
mv: no such file or directory: /Users/aliyasir/Documents/DEV-WIP/AIMINAABEE/bee-mobile/bee-mobile-TS/Aiminaabee/android/app/src/debug/java/com/rnnstarter/*
Error moving: "android/app/src/debug/java/com/rnnstarter" "android/app/src/debug/java/com/rnnstarter"
/android/app/src/main/AndroidManifest.xml MODIFIED
/android/app/_BUCK MODIFIED
/android/app/build.gradle MODIFIED
Done removing builds.
APP SUCCESSFULLY RENAMED TO "Aiminaabee"! 🎉 🎉 🎉
Podfile has been modified, please run "pod install" inside ios directory.
Please make sure to run "watchman watch-del-all" and "npm start --reset-cache" before running the app.
✨  Done in 9.68s.

**Comment by kanzitelli** [comment]
hi @Yasir5247. I have just followed the same steps you provided and this what I got:
![Screenshot 2021-07-13 at 14 37 10](https://user-images.githubusercontent.com/4402166/125452934-233cb07d-0a49-4a8e-a20c-a7519ca42f04.png)
![Screenshot 2021-07-13 at 14 37 56](https://user-images.githubusercontent.com/4402166/125452959-5c7efa85-fa96-41d2-8b72-980c3d29be69.png)

I couldn't reproduce your error, unfortunately. As an option, you can try using `cli-rn` how described in [Quick start](https://github.com/kanzitelli/rnn-starter#quick-start-with-cli-rn) section.

**Comment by leicaand** [comment]
Same problem here

**Comment by kanzitelli** [comment]
@Yasir5247 @leicaand you can also try [react-native-rename-next](https://github.com/mayconmesquita/react-native-rename-next)

**Comment by Yasir5247** [comment]
![photo_2022-01-17_10-35-13](https://user-images.githubusercontent.com/472971/149713517-3f39a286-950a-4d48-8d25-2887e578912c.jpg)

renaming the project still doesnt work for me. i tried with windows, and with a friends computer. still ios directory folders name starts with RNNStarter. what am i missing here. 

my app.json file. 
{
  "name": "Aiminaabee",
  "displayName": "Aiminaabee"
}
