### ISSUE TITLE
Issue of Eslint latest versioning

### ISSUE THREAD

**Issue by rizwanatta** [kanzitelli/rnn-starter#61]
- Eslint versioning is causing Eslint Failure had to revert back to 

    "eslint": "^7.14.0"
    
  in order get passed to warnings and errors and lint being able to work in Webstorm or VsCode
  
  cc @kanzitelli  did you get it working ( RN latest version supports older Eslint package )

**Comment by kanzitelli** [comment]
Hey @rizwanatta! Thanks for raising this up! I don't see any issues with Eslint on my machine with rnn-starter and everything seems to be working with the latest version. Can you elaborate more on that?
