### ISSUE TITLE
Flipper not able to pick the application from Simulator 

### ISSUE THREAD

**Issue by rizwanatta** [kanzitelli/rnn-starter#64]
attached image show even though the application is on i am unable to see the application in FLIPPER

## what i have done so far is 
-  I have unCommented the code for initilasing Flipper in MainApplication.java file
- i am able to see hermes based logs 
- but Network plugin is what i wanna keep eye on ( which becomes unavailable ) 

## QUESTION

are there any other steps that we should do to enable flipper #whyItsCommentedOnFirstPlace

<img width="1440" alt="Screenshot 2021-12-22 at 9 28 30 AM" src="https://user-images.githubusercontent.com/22873095/147035667-77de2126-ffd2-4b3a-97d2-8d370d20ed41.png">

**Comment by kanzitelli** [comment]
Hi @rizwanatta!

I am seeing the same screen as you do.
Why was it commented in the first place? Honestly, I don't remember but probably it was breaking something.

I don't usually use any debugging tools like Flipper, I go straight with Xcode or Android Studio, and terminal for logs.
But it's strange that it's not working, everything seems to be set up correctly.

Try to reach out Discord channel of RNN, the issue might be with it.

**Comment by rizwanatta** [comment]
@kanzitelli hi!

i am pretty sure its how rnn-starter is set up, i am using RNN in another navigation app and it works just fine with Flipper , for now with rnn-starter i am using Reactotron to Trace Network logs and stuff but will be looking for a solution ASAP! and will raise a PR for it

**Comment by kanzitelli** [comment]
Hello @rizwanatta!

That also might a reason, right. If you would find a solution, you are more than welcome to create a PR. Thank you!

**Comment by kanzitelli** [comment]
hey @rizwanatta!

So it's working for me now. I don't know what exactly fixed the problem but it started working after updating all the packages and updating Flipper.

<img width="1280" alt="Screenshot 2021-12-30 at 23 34 31" src="https://user-images.githubusercontent.com/4402166/147795490-9c81f4ec-d258-476d-b576-5f8e69a5b90b.png">

I will publish the update asap. But there is another issue with `react-native-reanimated` which crashes the app on reload action. The issue progress with Reanimated 2 is [here](https://github.com/software-mansion/react-native-reanimated/issues/2702).
