### ISSUE TITLE
Renaming the app doesn't work

### ISSUE THREAD

**Issue by Yasir5247** [kanzitelli/rnn-starter#70]
This is the command i'm using to install the starter 

cli-rn new Aiminaabee -b com.aiminaabee.pro -t rnn

However still the ios directory name is RNNStarter. 

I tried with sudo too. 

any ideas?

**Comment by kanzitelli** [comment]
@Yasir5247 I can not reproduce this. When I run the command you sent I get the following

![Screenshot 2022-01-18 at 11 21 13](https://user-images.githubusercontent.com/4402166/149918954-b30e36de-65e0-4ab0-b52d-48b01a5623d4.png)

**Comment by Yasir5247** [comment]
![photo_2022-01-17_10-35-13](https://user-images.githubusercontent.com/472971/149975753-36d88b29-68b4-40b7-8419-9192f617c55c.jpg)

i'm not sure why it cant file the file as seen the screen shot

**Comment by kanzitelli** [comment]
@Yasir5247 I think `react-native-rename` doesn't support Windows. If you look closely, you will see that Windows has `D:\node\MoonApp` path, however `react-native-rename` is trying to access `D:/node/MoonApp` where slashes are different. Probably this is what causing a problem.

Try using [`react-native-rename-next`](https://github.com/mayconmesquita/react-native-rename-next) which, as they state, has Windows support :)

**Comment by Yasir5247** [comment]
I couldn't get it on my mac so i tried using windows.  doesnt have to do anything with NPM or node version. 

mine is: 

node: v16.13.1
npm: 8.3.1

**Comment by kanzitelli** [comment]
did you try react-native-rename-next?

**Comment by Yasir5247** [comment]
@kanzitelli hi, react-native-rename-next worked. Thank you as always. :)
