### ISSUE TITLE
Writing Tests for a single Function causes Dilema of test failures

### ISSUE THREAD

**Issue by rizwanatta** [kanzitelli/rnn-starter#72]
hey @kanzitelli  ! love this template! i am having couple of issues while testing ! i able to mock every other package i introduced in the template above your provided ones. but the react-native-ui-lib's usage in DesignSystem is not by passing the mocks at all

any solution on that or insight ! a  mock folder you wrote for the tests ?

**Comment by kanzitelli** [comment]
@rizwanatta hey! thank you! I have not set up any tests for this template yet and been using mostly e2e tests. If there is any issues with RN UI Lib, try to reach them through opening issue or Discord channel.
