### ISSUE TITLE
Top bar button on Android TV

### ISSUE THREAD

**Issue by hotrush** [kanzitelli/rnn-starter#73]
Hello, regarding your boilerplate for tv - is it possible to make left/right buttons in top bar focusable? I mean select and click them using remote keys or keyboard arrow buttons?

**Comment by kanzitelli** [comment]
Hey @hotrush. This starter has not been tested on TV devices. However, there is some work done in that direction -- https://github.com/react-native-tvos/rnn-starter-tv. Also, you can check more examples in [react-native-tvos](https://github.com/react-native-tvos).

**Comment by hotrush** [comment]
I was talking about https://github.com/react-native-tvos/rnn-starter-tv actually, issues are disabled there. Missed that owners are different for these repos, sorry.
