### ISSUE TITLE
[Module request] Please support native drawer | side menu

### ISSUE THREAD

**Issue by phathuynh5519** [kanzitelli/rnn-starter#80]
Folks, most of mobile apps need drawer, please help integrate it into the starter kit
https://raw.githubusercontent.com/LukeBrandonFarrell/open-source-images/master/react-native-navigation-drawer-extension/left-drawer.gif
https://raw.githubusercontent.com/LukeBrandonFarrell/open-source-images/master/react-native-navigation-drawer-extension/bottom-drawer.gif
Ref: https://github.com/lukebrandonfarrell/react-native-navigation-drawer-extension
Cheers,

**Comment by kanzitelli** [comment]
I would not agree that most of mobile apps need drawer. It's better to use tabs, more UX friendly. Plus, the drawer is not officially supported by RNN, it's just a workaround. However, if you'd like to use that library, I believe that there is easy installation instructions.
