### ISSUE TITLE
[Module request] Support Styled component

### ISSUE THREAD

**Issue by phathuynh5519** [kanzitelli/rnn-starter#81]
Folks, we love your work and effort, please help expand our communities by supporting Styled component developers to enable their communities to approach our rnn-starter kit faster, more friendly and more intuitively thanks to their current front-end stacks
Ref:
1. [https://styled-components.com/docs/faqs](https://styled-components.com/docs/faqs)
2. [https://blog.logrocket.com/how-to-use-styled-components-with-react-native/](https://blog.logrocket.com/how-to-use-styled-components-with-react-native/)
3. 
![image](https://user-images.githubusercontent.com/59623591/156261165-aee1faef-3429-4c72-88c7-4f257fdb1273.png)

**Comment by kanzitelli** [comment]
I do not see any point of doing so. `styled-components` library was used before in this starter but was replaced in favour to RN UI Lib as it's created specifically for RN and supports design system which is important. However, `styled-components` could be easily installed and used in any project.
