### ISSUE TITLE
Back event does not work when on root activity

### ISSUE THREAD

**Issue by FawadMahmood** [kanzitelli/rnn-starter#99]
firstly thank you for such great work and keeping this repo updated.

When we are on the root activity back button does not work, maybe a bug from Wix native navigation.

Also crashes on release complete and sometimes on debug.

**Comment by kanzitelli** [comment]
hey @FawadMahmood! glad to hear that!

could you provide more information about your navigation and screens structure? are you using rnn-screens? any extra logs, video or reproduction repo would be also helpful :)

**Comment by FawadMahmood** [comment]
Well, there are a few issues I see, 

Release build crashes with the following error 

couldn't find DSO to load: libjscexecutor. so 
also 
couldn't find DSO to load: liberties-executor-debug. so 

To reproduce, please just create a release build of the same working repo of this codebase. 

Secondly, for the back button issue, you can try pressing the hardware back button on the root activity of tabs.

**Comment by FawadMahmood** [comment]
I am sharing error issues in Latest version of this repo without making any changes.

**Comment by kanzitelli** [comment]
There are a lot of issues regarding “Couldn’t find DSO to load” in react-native repository. For example, this solution helps people — https://github.com/facebook/react-native/issues/25537#issuecomment-1182498993

Hardware back button from root activity is broken indeed. I just tested and it freezes navigation for the same times you press on back button. Probably, that’s the issue with RNN and latest changes in 7.30.0-alpha1 where they have added support for “predictive” navigation.

I’m currently on the vacation and will try to ship RN 0.70 asap to be able to test that.
Also it will make sense to try RNN 7.30.0-alpha (not alpha1), maybe it’ll work. But it will need some native code changes (not big ones tho) as Kotlin versions are different.

**Comment by FawadMahmood** [comment]
Hello brother, I have a working of this repo on React Native .70, I can send a pull request or can share the repo with you. 

That has no release build issues I have checked.

Also, there’s one more issue I see, using withObserver causing an issues with React Native fast refresh on screens.

**Comment by kanzitelli** [comment]
Yes, sure, PR would be great!
Because I’ve started RN 0.70 integration to [starters-dev/rnn-with-expo](https://github.com/starters-dev/rnn-with-expo) (that’s where i test first), but had problems with iOS part and Hermes framework not being found. There are some open issues and a solution (but not a stable one). 

But still I had the issue with back button on RN 0.70 and RNN 7.30.0-alpha1. Do you see that error or it’s gone? Maybe it’s just my old Android device.

And what do you mean by issues with withObserver? Never experienced that. There were usually problems with RNN and fast refresh (reload) but I don’t remember seeing them lately.

**Comment by FawadMahmood** [comment]
No the back button issue is still there, even I have upgraded react native and expo, 

- to check the fast refresh issue please try to change anything on any screen it'll not show fast refresh changes on device, however it works for the components, but all components using withObserver it is not working.

**Comment by kanzitelli** [comment]
Yeah, that is right, didn't mention it before 😄 so just remove `withObserver` and wrap each screen with `observer(...)`. I've sent the commit.

**Comment by FawadMahmood** [comment]
> Yeah, that is right, didn't notice it before 😄 so just remove `withObserver` and wrap each screen with `observer(...)`. I've sent the commit.

Yes it does fixes the issue, Thank you.

I have sent the pull request with v.70 React Native and tested it with 2 working projects already, I see no issues so far.

**Comment by kanzitelli** [comment]
Hello @FawadMahmood! Thank you for your contribution! I have created another PR and mentioned you as a co-author.

**Comment by FawadMahmood** [comment]
Happy to see this new update, Thank you for keeping this repository updated, it really help :)
